add_newline = false
format = """$username\
$hostname\
$directory\
$character
"""

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[username]
format = "[$user]($style)"

[hostname]
format = ":[$hostname]($style) "